[package]
authors = ["Jacob Brown <kardeiz@gmail.com>"]
name = "awmp"
version = "0.3.0"
description = "An easy to use wrapper around multipart fields for Actix web"
keywords = ["actix", "actix-web", "multipart"]
license = "MIT"
repository = "https://github.com/kardeiz/awmp"
readme = "README.md"
edition = "2018"

[dependencies]
actix-web = "1"
actix-multipart = "0.1"
futures = "0.1"
mime = "0.3.13"
mime_guess = "2"
tempfile = "3.1.0"
url = "1"
flate2 = "1.0.10"
bytes = "0.4.12"
sanitize-filename = "0.2.1"

[dependencies.uuid]
features = ["v4"]
version = "0.7.4"
